# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0022_auto_20160606_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tester',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
