# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QieCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.IntegerField()),
                ('location', models.CharField(default='', max_length=100)),
                ('comments', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tester', models.CharField(choices=[('abaas', 'Andrew Basa'), ('csmith', 'Caleb Smith'), ('jpotarf', 'Jordan Potarf'), ('asmith', 'Adryanna Smith'), ('jlawrence', 'John Lawrence')], default='', max_length=100)),
                ('date_tested', models.DateTimeField(verbose_name='date tested')),
                ('test_type', models.CharField(choices=[('RCT', 'Really Cool Test'), ('SCT', 'Sort of Cool Test')], default='RCT', max_length=3)),
                ('passed', models.BooleanField()),
                ('comments', models.CharField(default='', max_length=1000)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qie_cards.QieCard')),
            ],
        ),
    ]
