# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='tester',
            field=models.CharField(default='', max_length=100),
        ),
    ]
