# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0005_auto_20160603_0836'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='Attempt',
        ),
    ]
