# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0007_attempt_attempt_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='attempt_num',
            field=models.IntegerField(default=1),
        ),
    ]
