# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 15:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import qie_cards.models


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0008_auto_20160603_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qiecard',
            name='card_id',
            field=models.CharField(default='', max_length=7, validators=[qie_cards.models.validate_id, django.core.validators.RegexValidator(code='nomatch', message='ID length has to be 7', regex='^.{7}$')]),
        ),
    ]
