# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0010_auto_20160603_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='test_type',
            field=models.CharField(choices=[(b'RCT', b'Really Cool Test'), (b'SCT', b'Sort of Cool Test'), (b'RAT', b'Really Average Test')], default='RCT', max_length=3),
        ),
    ]
