# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0012_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='tester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qie_cards.User'),
        ),
    ]
