# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 18:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0013_auto_20160603_1339'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Tester',
        ),
    ]
