# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0014_auto_20160603_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(default='', max_length=100)),
                ('long_name', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
