# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0015_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='long_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='attempt',
            name='test_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qie_cards.Test'),
        ),
    ]
