# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0017_auto_20160603_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='attempt',
            name='test_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qie_cards.Testl'),
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
