# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0021_auto_20160606_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tester',
            name='username',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
