# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0022_auto_20160606_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='tester',
            name='email',
            field=models.EmailField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
