# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import qie_cards.models


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0025_test_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qiecard',
            name='card_id',
            field=models.CharField(default='', max_length=7, unique=True, validators=[qie_cards.models.validate_id]),
        ),
    ]
