# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0028_auto_20160608_0844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attempt',
            old_name='rejected',
            new_name='revoked',
        ),
    ]
