# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import qie_cards.models


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0029_auto_20160608_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qiecard',
            name='location',
        ),
        migrations.AddField(
            model_name='attempt',
            name='log_comments',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='attempt',
            name='log_files',
            field=models.FileField(default='default.png', upload_to='uploads/%Y-%m-%d/'),
        ),
        migrations.AddField(
            model_name='qiecard',
            name='geo_loc',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='qiecard',
            name='plane_loc',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='qiecard',
            name='uid',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='comments',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='image',
            field=models.ImageField(default='default.png', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='qiecard',
            name='card_id',
            field=models.CharField(blank=True, default='', max_length=7, unique=True, validators=[qie_cards.models.validate_id]),
        ),
        migrations.AlterField(
            model_name='qiecard',
            name='comments',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
