# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0032_auto_20160609_0901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attempt',
            old_name='log_files',
            new_name='log_file',
        ),
    ]
