# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qie_cards', '0035_auto_20160609_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='qiecard',
            name='humidity',
            field=models.FloatField(default=-999.9),
        ),
        migrations.AddField(
            model_name='qiecard',
            name='temperature',
            field=models.FloatField(default=-999.9),
        ),
    ]
